name: Run Android Emulator with Video Recording

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_LEVEL: 30               # Versão mais recente da API
      TARGET: google_apis         # API do Google
      CPU: x86_64                 # Arquitetura x86_64
      EMULATOR_NAME: test-emulator

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        sudo systemctl enable --now libvirtd
      shell: bash

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        target: ${{ env.TARGET }}
        arch: ${{ env.CPU }}
        channel: 'stable'

    - name: Clean Android SDK Cache and Update
      run: |
        rm -rf ~/.android/*
        rm -rf $ANDROID_HOME/.android/*
        sdkmanager --no_https --update
      shell: bash

    - name: Install SDK Components
      run: |
        sdkmanager --no_https --install "platform-tools" "emulator" "system-images;android-${API_LEVEL};google_apis;${CPU}"
      shell: bash

    - name: List SDK Repositories
      run: sdkmanager --list
      shell: bash

    - name: Install Specific System Image
      run: |
        sdkmanager --no_https "system-images;android-${API_LEVEL};google_apis;${CPU}"
      shell: bash

    - name: Create AVD
      run: |
        echo "Creating AVD..."
        echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "system-images;android-${API_LEVEL};google_apis;${CPU}" --force
      shell: bash

    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-audio -no-snapshot-load -gpu off -no-cache -no-metrics &
        adb wait-for-device
      shell: bash

    - name: Diagnostic Check - List Connected Devices
      run: adb devices
      shell: bash

    - name: Wait for Emulator to be Fully Booted
      run: |
        boot_completed=false
        timeout=0
        while [ "$boot_completed" != "1" ] && [ $timeout -lt 300 ]; do
          sleep 5
          timeout=$((timeout+5))
          boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
          echo "Waiting for emulator to fully boot... ($timeout seconds elapsed)"
        done

    - name: Start Video Recording
      run: |
        adb shell screenrecord /sdcard/emulator_run.mp4 &
      shell: bash

    - name: Wait for Emulator to Run for 1 Minute
      run: sleep 60

    - name: Stop Video Recording and Pull Video
      run: |
        adb shell pkill -l2 screenrecord || echo "Screenrecord may not have been running"
        adb pull /sdcard/emulator_run.mp4 .
      shell: bash

    - name: Upload Video as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: emulator-run-video
        path: emulator_run.mp4
