name: Run Android Emulator with Video Recording

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_LEVEL: 30           # Nível da API do Android desejado
      TARGET: google_apis      # Tipo de imagem (altere para `default` se preferir)
      CPU: x86_64              # Arquitetura do processador
      EMULATOR_NAME: test-emulator

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        sudo systemctl enable --now libvirtd

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        target: ${{ env.TARGET }}
        arch: ${{ env.CPU }}
        channel: 'stable'

    - name: Create AVD
      run: |
        echo "Creating AVD..."
        echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "system-images;android-${API_LEVEL};${TARGET};${CPU}" --force
      shell: bash

    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-snapshot -no-audio -no-window &
        adb wait-for-device
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0

    - name: Start Video Recording
      run: |
        adb shell screenrecord /sdcard/emulator_run.mp4 &
      shell: bash

    - name: Wait for Emulator to Run for 1 Minute
      run: sleep 60

    - name: Stop Video Recording and Pull Video
      run: |
        adb shell pkill -l2 screenrecord
        adb pull /sdcard/emulator_run.mp4 .
      shell: bash

    - name: Upload Video as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: emulator-run-video
        path: emulator_run.mp4
