name: Android Emulator with TikTok Web

on:
  push:
    branches:
      - main

jobs:
  run_emulator:
    runs-on: ubuntu-latest
    steps:
      # Instalar dependências essenciais
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip

      # Baixar e instalar o Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      # Configurar variáveis de ambiente
      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Verifying sdkmanager location..."
          ls $HOME/android-sdk/cmdline-tools/latest/bin

      # Aceitar licenças e instalar componentes do SDK
      - name: Install SDK components
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      # Criar e iniciar o emulador
      - name: Start Emulator with Google Play
        run: |
          echo "no" | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64" --force
          $HOME/android-sdk/emulator/emulator -avd test_avd -no-snapshot -no-window -no-boot-anim -accel off -no-metrics &
          adb wait-for-device
          sleep 120  # Aguarda 120 segundos para garantir que o emulador inicializou

      # Aguardar inicialização do emulador
      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          boot_completed=0
          while [ "$boot_completed" -ne 1 ]; do
            boot_completed=$(adb shell getprop sys.boot_completed)
            echo "Aguardando inicialização do emulador..."
            sleep 5
          done
          echo "Emulador inicializado com sucesso!"

      # Gravar o vídeo durante a execução do emulador
      - name: Start Screen Recording
        run: |
          adb shell mkdir -p /data/local/tmp  # Garante que o diretório existe
          adb shell screenrecord /data/local/tmp/tiktok_recording.mp4 &
          sleep 120  # Tempo de gravação. Ajuste conforme necessário.

      # Parar a gravação após o tempo
      - name: Stop Screen Recording
        run: |
          adb shell killall -2 screenrecord || echo "Nenhum processo de screenrecord encontrado para interromper"
          adb pull /data/local/tmp/tiktok_recording.mp4 ./tiktok_recording.mp4 || echo "Arquivo de gravação não encontrado"

      # Fazer upload do vídeo gravado
      - name: Upload Video Recording
        uses: actions/upload-artifact@v4
        with:
          name: tiktok_recording
          path: ./tiktok_recording.mp4
